name: Check
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Yarn install
              run: npm i -g yarn
            - name: Install dependencies
              run: yarn i
            - name: Lint
              run: yarn lint
    test:
      needs: [ lint ]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Unit tests
          run: yarn test
        - name: e2e tests
          run: yarn test:e2e
